<a href="https://colab.research.google.com/github/RogerHeederer/ML_practice_MyFirstML_B/blob/master/BernoulliNB_SpamClassfication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

source reference : https://github.com/wikibook/machine-learnin

**위 레퍼런스를 참조하여 공부하였으며, 필요하다고 생각되는 부분에 추가적인 설명 ,코드 추가, 그림 삽입 등을 덧붙였습니다.**


In [3]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score
np.random.seed(5)

In [4]:
email_list = [
                {'email title': 'free game only today', 'spam': True},
                {'email title': 'cheapest flight deal', 'spam': True},
                {'email title': 'limited time offer only today only today', 'spam': True},
                {'email title': 'today meeting schedule', 'spam': False},
                {'email title': 'your flight schedule attached', 'spam': False},
                {'email title': 'your credit card statement', 'spam': False}
             ]
df = pd.DataFrame(email_list)

In [5]:
df

email title   spam
0                      free game only today   True
1                      cheapest flight deal   True
2  limited time offer only today only today   True
3                    today meeting schedule  False
4             your flight schedule attached  False
5                your credit card statement  False

In [6]:
##데이터 트리밍##
#베르누이 나이브베이즈는 숫자만을 다루기 때문에, True, False를 1과 0으로 치환

In [8]:
df['label'] = df['spam'].map({True:1, False:0})
df

email title   spam  label
0                      free game only today   True      1
1                      cheapest flight deal   True      1
2  limited time offer only today only today   True      1
3                    today meeting schedule  False      0
4             your flight schedule attached  False      0
5                your credit card statement  False      0

In [9]:
#학습 데이터와 학습 데이터의 정답 분류
df_x=df["email title"]
df_y=df["label"]

In [48]:
cv = CountVectorizer(binary=True)
x_traincv = cv.fit_transform(df_x)

**CountVectorizer 함수를 통해서 email_title에 있는 단어의 갯수를 전부 수집.**<br/>
**free, game, only, today ......statement 총 17개 단어**<br/>
**그리고 그 크기를 기준을 삼아 벡터로 인코딩(표현)하는 함수이다**<br/>
**중복되서 나오는 단어는 0으로 표시한다**<br/>
**limited time offer only today only today: [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0]**

In [49]:
cv

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [52]:
x_traincv.toarray()

array([[0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]])

In [53]:
encoded_input = x_traincv.toarray()

In [54]:
#벡터로 인코딩된 이메일 제목 디코딩하기

In [55]:
cv.inverse_transform(encoded_input[0])

[array(['free', 'game', 'only', 'today'], dtype='<U9')]

In [56]:
cv.inverse_transform(encoded_input[1])

[array(['cheapest', 'deal', 'flight'], dtype='<U9')]

In [61]:
#각 단어의 인덱스가 어떤 단어를 가르키는지 알아보기
cv.get_feature_names()

['attached',
 'card',
 'cheapest',
 'credit',
 'deal',
 'flight',
 'free',
 'game',
 'limited',
 'meeting',
 'offer',
 'only',
 'schedule',
 'statement',
 'time',
 'today',
 'your']

##베르누이 나이브베이즈 분류##

In [87]:
bnb = BernoulliNB()
y_train=df_y.astype('int')
bnb.fit(x_traincv,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [153]:
# 테스트 데이터 트리밍
test_email_list = [
                {'email title': 'free flight offer', 'spam': True},
                {'email title': 'hey traveler free flight deal', 'spam': True},
                {'email title': 'limited free game offer', 'spam': True},
                {'email title': 'today flight schedule', 'spam': False},
                {'email title': 'your credit card attached', 'spam': False},
                {'email title': 'free credit card offer only today', 'spam': False}
             ]

In [144]:
test_df = pd.DataFrame(test_email_list)

In [145]:
test_df

email title   spam
0                  free flight offer   True
1      hey traveler free flight deal   True
2            limited free game offer   True
3              today flight schedule  False
4          your credit card attached  False
5  free credit card offer only today  False

In [146]:
test_df['label'] = test_df['spam'].map({True:1, False:0})

In [147]:
test_df

email title   spam  label
0                  free flight offer   True      1
1      hey traveler free flight deal   True      1
2            limited free game offer   True      1
3              today flight schedule  False      0
4          your credit card attached  False      0
5  free credit card offer only today  False      0

In [148]:
test_x = test_df["email title"]
test_y = test_df["label"]
x_testcv = cv.transform(test_x)
x_testcv2 = cv.fit_transform(test_x)
## 문제 상황. 책에서 제시하는 test_email의 단어 갯수는 총 15개
## 모델에게 트레인 시킨 email의 단어 갯수는 총 17개
## prediction할 때, 훈련한 모델의 파라미터 갯수와, 테스트의 파라미터 갯수가 맞지 않는다고 나온다
## 그리고 한 가지 더 의문, fit_transform과 transform의 차이가 뭔지 알아보기 위해 데이터를 수정해봤는데,
## 4번 인덱스와 5번 인덱스에  텍스트 lala, haha, hoho를 추가했다. 그 후 실행을 해보면
## transform은 증가된 단어의 갯수를 반영하지 못하고, fit_transform은 바로 반영한다.
## 그런데?? 이상하게, test_email_list 정의 실행문을 다시 한번(즉 2번 shift+enter) 실행해주면, transform도 늘어난 데이터수를 반영한다.


**책에서 제공하는 예문은 잘 실행된다. 테스트 단어 갯수가 15개임에도 불구하고, x_testcv를 찍어보면 6 x 17 matrix로 나온다.. 내가 테스트 하는 과정에서 fit_transform을 먼저 썻는데 이게 문제가 된거 같다.

**fit_transform을 테스트 데이터셋에 먼저 적용함으로써, 뭔가 데이터에 fit 하는 과정이 다시 발생하여, 기존 트레인 데이터에 적용되었던 6x17 형태가 -> 6x15 형태로 변한 것 같다. fit_transform의 자세한 기능은 좀 찾아봐야겠다

##결론은 책에서 제시하는 예문처럼 
## x_traincv= cv.fit_transform 그 후에  x_testcv=cv.transform을 썻으면 
## 훈련 데이터셋에 맞춰 fit한 6 x 17 형태가 그대로 살아있기 때문에,
## test 셋의 단어 갯수가 15개라도 feature 형태는 변함없기 때문에 모델 적용이 된다.

In [154]:
x_testcv

<6x18 sparse matrix of type '<class 'numpy.int64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [150]:
x_testcv2

<6x15 sparse matrix of type '<class 'numpy.int64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [107]:
x_testcv.toarray()

array([[0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0]])

In [108]:
x_testcv2.toarray()

array([[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0]])

In [110]:
predictions=bnb.predict(x_testcv2)

In [112]:
accuracy_score(test_y, predictions)

0.6666666666666666