<a href="https://colab.research.google.com/github/RogerHeederer/ML_practice_MyFirstML_B/blob/master/MultiClassfication_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

source reference : https://github.com/wikibook/machine-learnin

**위 레퍼런스를 참조하여 공부하였으며, 필요하다고 생각되는 부분에 추가적인 설명 ,코드 추가, 그림 삽입 등을 덧붙였습니다.**


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import mnist
from numpy as np

SyntaxError: ignored

In [ ]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [ ]:
X_train.shape, X_test.shape

((60000, 28, 28), (10000, 28, 28))

In [ ]:
y_train.shape, y_test.shape

((60000,), (10000,))

In [ ]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [ ]:
#데이터 정규화 - 모델이 경사하강법을 더 수월하게 할 수 있게 해준다.
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

In [ ]:
X_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [ ]:
print("train target (count) : " + str(y_train.shape))
print("test target (count) : " + str(y_test.shape))

train target (count) : (60000,)
test target (count) : (10000,)


In [ ]:
print("sample from train : " + str(y_train[0]) )
print("sample from test : " + str(y_test[0]) )

sample from train : 5
sample from test : 7


In [ ]:
# 2차원 데이터를 1차원으로 flatten(단순화) 시키기
# 단순화 기법에는 3가지가 있다. ravel(), reshape(), flatten()
# ravel() : 1차원 배열은 반환
# reshape() : 데이터 변경 없이 형상만 변경하여 반환
# flatten() : 1차원 배열 복사본을 반환

In [ ]:
input_dim = 784 #28*28
X_train = X_train.reshape(60000, input_dim)
X_test = X_test.reshape(10000, input_dim)

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(60000, 784)
(60000,)
(10000, 784)
(10000,)


In [ ]:
# x값은 정규화 해줬고, 예측으로 나온 확률값(소프트맥스 통해 나온 값이니까)과 실제 y값을 비교해주려면
# y값이 one-hot-encoding 되어야 10 차원의 벡터를 가지게 된다.
num_classes = 10
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

print(y_train[0])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [ ]:
model = Sequential()
model.add(Dense(input_dim = input_dim, units=10, activation = 'softmax'))
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=2048, epochs=100, verbose=0)

In [ ]:
score = model.evaluate(X_test, y_test)
print('Test accuracy:', score[1])

313/313 [==============================] - 0s 859us/step - loss: 0.4197 - accuracy: 0.8917
Test accuracy: 0.891700029373169


In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 10)                7850      
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.layers[0].weights

[<tf.Variable 'dense_1/kernel:0' shape=(784, 10) dtype=float32, numpy=
 array([[ 0.02095659, -0.07958502,  0.04045943, ..., -0.07138617,
          0.00355845, -0.00177529],
        [ 0.02481782, -0.02876443, -0.04153794, ...,  0.06914505,
          0.04659536, -0.00706606],
        [ 0.05671059, -0.06783432,  0.01402701, ..., -0.04995856,
          0.04100614,  0.05726159],
        ...,
        [ 0.04355077, -0.05626863, -0.03939598, ...,  0.0770665 ,
         -0.07575781,  0.06681076],
        [-0.00682398, -0.07378633,  0.01401687, ..., -0.08523445,
          0.06081527,  0.01890483],
        [ 0.04440401,  0.04066729, -0.02736366, ..., -0.07777335,
          0.05253229,  0.08075363]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=
 array([-0.08321292,  0.15992482, -0.02405666, -0.04912386,  0.04887216,
         0.15859082, -0.02821795,  0.1045289 , -0.24232613, -0.04497923],
       dtype=float32)>]